### ISSUE TITLE
Interacting With Old Kasuto's Sign Can Cause Unwanted Behavior

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#10]
In Old Kasuto, after killing a Moa and interacting with the sign while the experience is counting up, the game may completely lock up (on emulator) or teleport the player into the wall/ceiling down in the old man's basement (MiSTer FPGA), forcing a reset/Up+A.

Video Examples:
Emulator: https://clips.twitch.tv/PluckyCharmingSamosaPanicVis-nK7-qcjQQCQX1EZw (Warning: Loud/Language)
MiSTer FPGA: https://clips.twitch.tv/BovineTameDunlinShadyLulu-AyTP0srlpZdWV00v

When attempting to trigger the bug, it seems that either a seed may not be susceptible to it, or there is only a small window where it can occur, since this bug does not always appear.  However, now that I, and others, know that it exists, we are actively trying to avoid it, so that alone likely creates a bias in the feedback/evidence that we currently have.

In addition, I have not seen a single report of this happening on an actual NES console, but not only should the MiSTer's FPGA be close to replicating the old hardware, there are also fewer players using an NES.

**Comment by Ellendar** [comment]
https://clips.twitch.tv/TemperedTardyOcelotWow-WGDvUWd4wp7COgn8

**Comment by jroweboy** [comment]
Fixed in 4.4 https://github.com/Ellendar/Z2Randomizer/commit/d957d9568b42e80d24890e8d845d3946b545fd7a
