### ISSUE TITLE
Vertical Caldera Biomes Rarely Seen in Death Mountain

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#102]
The Death Mountain biome, when in Caldera form, can be vertically oriented, but it seems to be _incredibly_ rare.

Note: Adding issue as a reminder for patch notes.

**Comment by Ellendar** [comment]
Horizontal vs vertical was being determined extremely weirdly, using a random float comparison. Also it was being calculated multiple times in multiple places, so potentially creating weirdness. ALSO, it was being calculated per world generation attempt, so there was a strong survivorship bias. IsHorizontal is now determined on properties export on a per-continent basis via a simple rand(2) call.
