### ISSUE TITLE
"Include Lava in Shuffle" Flag Not Being Properly Set Under Specific Conditions (4.2.5)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#105]
The "Include Lava in Shuffle" flag is not being enabled when pasting a flagset into the Flags field that would otherwise have it enabled, _if_ "Shuffle Encounters" is not already enabled before the paste.

Steps to reproduce:

1. Copy any flagset that has "Include Lava in Shuffle" enabled.
2. Completely disable "Shuffle Encounters" on the Overworld tab.
3. Paste the flagset back into the Flags field and notice how "Include Lava in Shuffle" does not re-activate.
4. Paste the flagset into the Flags field one more time and now "Include Lava in Shuffle" activates.

I've confirmed that this is more than just a visual issue with the UI as it will create two different seeds with two different hashes because it's actually two slightly different flagsets.

**Comment by Ellendar** [comment]
This was fixed for 4.3 a while ago. Was a sequencing issue in update triggers
