### ISSUE TITLE
Suggestion: Split palace layout option into 2 parts

### ISSUE THREAD

**Issue by Jaylow7** [Ellendar/Z2Randomizer#113]
I mentioned this on the Z2R discord and was asked to put it here.

Would it be possible to split out the option for palace layouts into multiple settings? 
The idea is have one setting for p1-6 and a separate one for GP.
What I'm thinking here is I'd like the option to have p1-p6 with random layouts, but keep GP vanilla.

**Comment by Ellendar** [comment]
Probably merge some of the other settings into this, including possibly mirai's normalized dungeon lengths.
Possible lists:

Normal:
- Vanilla
- Shuffled
- Reconstructed
- Normalized
- Random

GP:
- Vanilla
- Shuffled
- Long
- Short
- Random
