### ISSUE TITLE
Candle Always Placed in a Palace When Shuffling Item Locations (4.2.7)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#118]
There is growing evidence that, when item locations are shuffled, the Candle is always* placed in a palace, rather than any other outside location.  More specifically, with the flagset that is being used for brackets in the 2023 Standard tournament:
`AAAN6AAFeqXtN1TZt0g$8v4SX#4XR7AALh`

I have not yet tried any other combination of flags to test this further, as it is currently tournament season.

_* A larger sample size may show that this is not always true, but so far, I do not believe I've played a seed where it wasn't._

**Comment by Ellendar** [comment]
There was a bug in the fisher-yates shuffle implementation for item shuffle that caused the first element in the list (candle) to never shuffle. This meant it was always in "palace 1", and then after palace shuffle, it was always in a palace. There was actually a more serious bug that only happened when mixed shuffle was off but overworld shuffle was on that could cause multiple locations to not shuffle properly that was also fixed as part of this pass.
