### ISSUE TITLE
Inconsistent Hint Behavior From Bot in Saria (4.2.7)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#120]
When the "Generate Bagu's Woods" flag is enabled, the bot in Saria will still sometimes give a hint for an item, rather than the hint for Bagu's location.

Example:
Flagset: `AAAN6AAFeqXtN1TZt0g$8v4SX#4XR7AALh`
Seed: `731235308`
Hint: `IN A MAZE\LIES THE\HAMMER.`

**Comment by Ellendar** [comment]
I found what causes this, but i'm going to route around the issue. I want the bagu's woods hint (if enabled) to be on the river man instead of on the bot so you can get it from both sides. This would mean the bot goes back to being a normal hint NPC all the time.

**Comment by Ellendar** [comment]
Moved bagu's woods hint to river man (index 36)
