### ISSUE TITLE
Application Stuck on Palace Generation (4.3.0 7a7e62d)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#126]
The application gets stuck at "Generating Palaces" when using the following flagset: `hEAEiqAFerX2WTSKkVeRf+2csmv@smiyAAWA`

Something to note, is that the `Include Vanilla Rooms` setting is disabled for palace layouts, and when it is re-enabled the seed will generate.  During my stream, someone in chat asked if palace entrances are considered to be "vanilla" rooms, and if so, are they not being included within the palace layout?  I didn't know the answer to that question, but figured that I'd leave it here in case that's what's occurring.

**Comment by Ellendar** [comment]
Stalled out due to an incorrect mapping on 4.0 rooms configuration -> properties causing the room pool to be always empty.
