### ISSUE TITLE
Death Valley Inaccessible (Chaos+Mountainous) (4.3.0 7a7e62d)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#127]
Death Valley is inaccessible on Eastern Hyrule.

Flagset: `hEAEiqAFerX12GSKtVeRf+2csmv@smiyAAWA`
Seed: `831025572`

**Comment by Ellendar** [comment]
When the overworld byte limit was exceeded, locations weren't reinitialized, so they still had canShuffle: false. This meant towns/caves would remember their locations incorrectly from their previous generation, but the map would be the new generation... with no towns/caves.

Added a reinitialization block at the start of the byte checked loop.
