### ISSUE TITLE
Seed Generation Issue (Chaos Climate) (4.3.0 7a7e62d)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#128]
The seed gets stuck* generating Western Hyrule with the following:

Flagset: `hEAEiqAFerX2WTSKtVeRf+2csmv@smiyAAWA`
Seed: `831025572`

_* I let it try to generate for ~3 minutes, but the text doesn't change, so I assume it's stuck._

Investigating further with the same seed, setting the Western Hyrule biome to "Islands" seems to cause the same issue where the seed will not generate, and manually selecting any other non-Vanilla biome does not cause the seed to get stuck at "Generating Western Hyrule."  I was also unable to find any other combination of biomes between the West or East that caused the same seed to fail generating with the "Chaos" climate setting.

Trying additional seeds to see if the behavior continues with the combination of Chaos climate and Island (West), and it does.  I even found a seed (`181694865`) that produced an actual error:

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/1e0110ed-a47a-42f0-ac6f-a49276acf5c6)

**Comment by Ellendar** [comment]
Chaos climate for islands west at seed terrain count 300 was consistently exceeding the overworld map byte limit by 100-200 bytes. For now i'm toning down the count to 220, which seems to make it work consistently, but I want to investigate if this can be conditionally scaled so other climates still generate a level of chaos consistent with their capability.

**Comment by Ellendar** [comment]
On second thought I just did the per biome terrain limit now.
