### ISSUE TITLE
Carock De-Spawns if Player Dies During Boss Fight (4.3.0 7a7e62d)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#129]
With jrowe's latest changes to Carock, he de-spawns if you die while fighting him.  The door before the gem pedestal is still present, and a gem can still be placed, but the boss goes missing.  He has been made aware of the issue and is investigating.

**Comment by MiR4i** [comment]
Played a few different seeds tonight and I tested Carock to see if the above behavior was still true in the latest version ([4.3.0 aae5d00](https://github.com/Ellendar/Z2Randomizer/commit/aae5d00fe89f322e5f1f3ec9bf7e3acea2eadfa7)), and it was not.  In three different seeds, both in the Vanilla boss room and an elevator-up boss room, Carock did not de-spawn after taking a death to him.

Will need to do further research on this issue.

**Comment by MiR4i** [comment]
With the latest release ([5ffac09](https://github.com/Ellendar/Z2Randomizer/commit/5ffac092e4d4697985ee0e970b032b648f169d18)), Carock can still de-spawn if the player takes a death on him, although not always.  What's also interesting, is that if Carock de-spawns, the trigger for placing the gem can also be moved forward into the boss room upon re-entering.  While the second bug is not always true along with the de-spawn, it does seem to trigger if you've previously placed a gem in a different palace before fighting Carock.

`hEAEkqAFestUWVRMMVeRgQ2cumv@tNiyAAWA`
`554241177`

Notes:
 * P4/P6/GP on the West
 * Carock = hold right at top of first elevator junction.
 * Barba = hold left at bottom of first elevator junction.
 * I did give myself everything _after_ the seed was created, so either Game Genie it up or use the editor to get yourself palace ready.

**Comment by Ellendar** [comment]
Jrowe pushed a fix for this.
