### ISSUE TITLE
Grass & Desert Tiles Oddly Surrounded by Graveyard Tiles (853305789) (4.3.0 7a7e62d)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#130]
On the overworld map, both the Grass and Desert tiles are oddly surrounded by graveyard tiles.  The Water tile, however, is not affected by this.

Flagset: `hEAEiqAFerX2WTVKtVeRf+2csmv@smiyAAWA`
Seed: `853305789`

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/41088766-f7bd-4e3f-8fd6-adb955adb9c0)

**Comment by Ellendar** [comment]
This is (probably) not a bug? Talk to me about this.
