### ISSUE TITLE
Some PBag Item Caves Inaccessible (853305789) (4.3.0 7a7e62d)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#132]
Both Heart Container Cave (West) and Sunken PBag Cave (East) are unreachable.

Flagset: `hEAEiqAFerX2WTVKtVeRf+2csmv@smiyAAWA`
Seed: `853305789`

Note: This was a custom flagset that I created to test a seed, but I forgot to enable `Include PBag Caves in Item Shuffle`, which may be the cause for the lack of access?

**Comment by Ellendar** [comment]
This was a consequence of a bug fixed in another ticket.
