### ISSUE TITLE
Broken Palace Layouts (Items Rooms and Bosses) (853305789) (4.3.0 7a7e62d)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#133]
Palace layouts in this seed are not okay.

Flagset: `hEAEiqAFerX2WTVKtVeRf+2csmv@smiyAAWA`
Seed: `853305789`

Where to begin...

* P1 (West) uses the Barba boss room, but Gooma is the boss, he's using Helmethead's sprite, and he is stuck in a pit of lava.
* P2 (West) is, surprisingly, just fine.
* P3 (East) has no boss room, but contains two item rooms, one of which is inaccessible.
* P4 (East-DV) uses Barba's boss room and Barba is the boss, not Carock.
* P5 (West) has Horsehead as the boss.
* P6 (MI) has no boss room, but contains two item rooms.
* GP (East) is fine until Dark Link's room, which, once again, uses Barba's boss room, and as a result, causes the game to lock up before being able to start the fight.

**Comment by Ellendar** [comment]
- Fixed a bug where P6 vanilla boss room was not marked as P6.
- In digshake's old code, the function that is supposed to select the boss room was also modifying the enemies because accessors should also modify data...
