### ISSUE TITLE
Rooms in Reconstructed Palaces Can Result in a Garbled Mess (4.3.0 aae5d00)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#137]
EDIT: Updated title to better reflect that not all rooms cause a lock-up, and it's more about just "bad" palace rooms being created and causing issues.

All of the seeds I reviewed tonight that used "Reconstructed" palace layouts had some palaces (not all) that contained rooms which caused a lock-up (black screen with only music playing).  In one seed, a few rooms did not cause a lock-up, but resulted in a jumbled mess of a layout.  Great Palace layouts seemed to be unaffected by these types of rooms, although I did only check three seeds.

Version: [4.3.0 aae5d00](https://github.com/Ellendar/Z2Randomizer/commit/aae5d00fe89f322e5f1f3ec9bf7e3acea2eadfa7)
Flags: `qNAJsqAFerYMWVRKtXeTgQ2csmv@suiyAAWA`
Seed: `289203995`
Examples:
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/b60dfc90-0a75-4cc5-b40c-1ba6bb9505ed)

\-------------------------------------------------

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/e7e03f59-8eff-406a-afe4-945bb3b0bbde)

**Comment by Ellendar** [comment]
The most likely cause of this is an error in the palace saving memory management, but jrowe completely redid that system, so even if I track a fix down, the problem won't exist anymore. (Likely replaced by new problems). Closing this and we can add new tickets as needed on the new release.
