### ISSUE TITLE
Multiple Thunderbird Rooms in Great Palace (4.3.0 aae5d00)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#138]
I'm submitting this as a bug, but I should be submitting it as a feature request.

While almost all of the Great Palace rooms are a complete mess in the editor, the entirety of it is traversable with no issues.  Both Thunderbird rooms functioned properly, and neither boss was affected by the other being killed (i.e. both Thunderbirds were considered separate bosses and could each be killed without the other acting like it had been defeated and not appearing in its own room).

Additional Details:
* One Thunderbird was on the route to Dark Link, while the other was not.
* "Thunderbird 50/50 Required" flag enabled.
* ~~I did not see this again in the few other GPs that I looked at tonight.~~ (See first reply)

Version: [4.3.0 aae5d00](https://github.com/Ellendar/Z2Randomizer/commit/aae5d00fe89f322e5f1f3ec9bf7e3acea2eadfa7)
Flags: `qNAJsqAFerYMWVRKtXeTgQ2csmv@suiyAAWA`
Seed: `289203995`
Notes: GP in Death Valley

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/4b02511e-3bc7-482f-812c-5b5981eda264)

**Comment by MiR4i** [comment]
Decided to keep looking, and I found an even better GP—Two Thunderbird rooms and ***three*** Dark Link rooms.

I was able to reach both Thunderbird rooms, as well as all three Dark Link rooms, but got stuck in the blocks on the third (bottom in the image below) and couldn't initiate the fight.

Flags: `+++e9Wx4erYMWVRKMXeTgx2tsmv@suiyAAWA`
Seed: `901299410`
Notes: GP on West (North)

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/befd9807-00cf-4b6c-8215-b512e9f5e836)

**Comment by Ellendar** [comment]
I did some tests and this is probably fixed as the result of a previous change, but I can't say for sure. Going to close this and if you see it again on a new release just reopen with that seed.
