### ISSUE TITLE
Barba Not Located in Expected P6 Boss Room (4.3.0 aae5d00)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#139]
In the following flagset/seed, Barba was located in a standard boss room.  The editor shows the P4 boss room in P6 and doesn't place any boss inside the room, but Barba is there.

Version: [4.3.0 aae5d00](https://github.com/Ellendar/Z2Randomizer/commit/aae5d00fe89f322e5f1f3ec9bf7e3acea2eadfa7)
Flags: `qNAJsqAFerYMWVRKtXeTgQ2csmv@suiyAAWA`
Seed: `289203995`
Notes: P6 on Eastern Hyrule

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/0fcb38ae-75c9-4a93-819f-51509837f279)

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/cbc1ccfd-e005-4f33-848b-bb213f61f2b3)

**Comment by Ellendar** [comment]
Fixed a bug where palaces 6/7 could spawn generic boss rooms.
