### ISSUE TITLE
Randomizer Stuck "Shuffling Items and Spells" (4.3.0 aae5d00)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#141]
In the following flagset/seed, the randomizer seems to be unable to shuffle items and spells.

Additional Notes:
* Sometimes, if I don't completely restart the application before attempting to generate this seed, it may get stuck on "Generating Palaces" instead.
* Giving myself every item and spell does not fix the issue (same seed, different flagset).

Version: [4.3.0 aae5d00](https://github.com/Ellendar/Z2Randomizer/commit/aae5d00fe89f322e5f1f3ec9bf7e3acea2eadfa7)
Flags: `AAAN6Wx4eqXjAAArtXgbg+2tsmv@suiyAAWA`
Seed: `643343853`

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/d1fa5ae2-c7cf-48cd-945f-a967e4c003dc)

**Comment by Ellendar** [comment]
Something in one of the dozen fixes I've made so far seems to have fixed this because it now generates almost instantly. If it comes up again I can reopen.
