### ISSUE TITLE
Infinite Seed Generation Time (4.3.0 0f9b4c2)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#143]
The following two flagsets/seeds don't seem to generate with the 4.3.0 [0f9b4c2](https://github.com/Ellendar/Z2Randomizer/commit/0f9b4c2212d3b947fbcc1392b4463590a4c9b85b) update.

`hEAJ8qAFerpMN1RK4Ve3QQ2csmv@suiyAAWA`
`599553030`

`hEAJ8qAFerpCc1RK4Ve3QQ2csmv@suiyAAWA`
`373174423`

I believe I got around the issue by forcing specific biomes for West and East Hyrule, but I don't exactly remember.

**Comment by Ellendar** [comment]
I fixed an issue that can cause this, but not sure if it's the only issue. Please continue to report seeds that don't work on the new version.
