### ISSUE TITLE
Incorrect Palace Layout Style (4.3.0 0f9b4c2)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#144]
The following flagset uses `Reconstructed` palace layout styles for both standard palaces and GP, but GP resulted in a completely Vanilla layout in the provided seed.

`hEAJ8qAFerpCc1RK4Ve3QQ2csmv@suiyAAWA`
`482381026`

**Comment by Ellendar** [comment]
The section of RandomizerConfiguration.Export that processed reconstructed random length incorrectly read from the normal palace style, causing PalaceStyle.RECONSTRUCTED_RANDOM_LENGTH to pass through to the logic, which effectively treated it as the null style.
