### ISSUE TITLE
Randomizer Allows User to Not Include Any Palace Rooms (4.3.0 0f9b4c2)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#152]
The randomizer currently allows a user to not include any palace rooms, resulting in a seed that, unsurprisingly, cannot move beyond the "Generating Palaces" step.  Presumably, this will also occur when both options are set to 50/50 and they both end up disabled.

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/2a4cf80c-befb-4ae5-b58f-71a698a94083)

**Comment by Ellendar** [comment]
Added a handler so at least one of vanilla/v4/v4.4 must be selected. Also updated the secondary validation in the configuration export to properly handle this and a few other cases.
