### ISSUE TITLE
Inconsistent CheckBox Behavior (4.3.0 0f9b4c2)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#153]
Attempting to enable one of these when the other is enabled results in inconsistent behavior.  The `By Layout/Enemies` option will override the `By Layout` one above it, but the reverse is not true.
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/5e7bd7e8-d42e-4f1f-a73a-b5423baf9703)

**Comment by Ellendar** [comment]
Three issues:

- The exclusivity handler wasn't considering the source of the request, so when it was handled both were checked and behavior was incorrect
- The two clauses in that handler weren't mutually exclusive, so weird stuff happened depending on the order checked.
- These two checkboxes were 3 state, even though the underlying option is only a normal bool. Updated them to be normal checkboxes.
