### ISSUE TITLE
Carock's Beam Patterns Affecting Other Enemies in Palace After Fight (4.3.0 5ffac09)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#159]
After Carock is engaged (and killed?) his beam patterns affect other enemies' pathing, as well as their projectiles while in the palace. This includes, but is probably not limited to:
 * Orange Iron Knuckles jumping/floating
 * Dripper drips being oddly affected by gravity
 * Dripper enemy spawn (e.g. Tinsuits) movement paths
 * Doomknocker's maces
 * Blue Iron Knuckle's beams

This doesn't seem to continue in other palaces after leaving P4, but I did not go back in to check if the behavior continued in P4 or not.

While some of this is a bit slow because I was trying to get some data, please refer to the several minutes at the end of this palace during my stream today: https://www.twitch.tv/videos/2024918160?t=4h27m20s

I'm not sure it matters on the flagset or seed, but here are the ones from the above video:
`hEAATqAFestUV3RrKVeNgQ2cumv@tNiyAAWA`
`814652626`

**Comment by jroweboy** [comment]
Fixed in 4.3
