### ISSUE TITLE
State leakage in palace generation. (4.3 B3)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#164]
EDIT: Thread title changed.

More research is needed here (and will be done), but I'm opening a ticket to document my current issue.

I played a seed on stream and forgot to change the `Beep Frequency` to my usual `Quarter Speed`, but when I started with only one heart container, the excessive beeping became a bit much after playing for about 30 minutes, and I decided to just re-generate the seed with the `Beep Frequency` changed because it shouldn't affect anything related to seed generation.  However, upon restarting the seed, the hash matched, but it was mostly different, and while I don't yet know why this happened, I'm including some screenshots to document what I'm referring to.

File Select Hash:
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/ed06baab-ba23-409c-ab90-17b6e6de2d7d)

Starting Loadout:
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/06b86c31-130a-49d5-a911-c01cbfe135ee)

North Palace Location:
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/0acc9905-54d8-4c01-8fa6-2ed718124157)

How many heart containers and which spells I started with, along with how many gems were required stayed the same, but here's a list of what I know that did change:
 * Biome type stayed the same (Mountainous), but overworld layout was different.
 * Palaces on the West were slightly different (2/3/4 vs 1/2/4)
 * Palace layout for P2 was different (didn't check P4 on first seed, but assume it was different)
 * Item locations on West were somewhat different, and those that were the same were in a different location.
 * Town-Spell assignments were different
 * Enemy shuffle was different

I doubt that there's much of a surprise that all of these things ended up changing after just one of them changed, but what's odd is that the hash didn't change.

Flagset: `hEAAjqAFestUV3StMVeRfxUcumv@tNiyAAWA`
Seed: `4545`

Now that this is all said and done, for me, simply changing the `Beep Frequency` in an attempt to reproduce the issue doesn't work anymore and the seeds are the same (as you would expect), but I have another test to run to see if I can replicate this.  That test is more involved and will have to wait until later, but I will report back whether my test is successful or not.

**Comment by MiR4i** [comment]
I'm onto something...
 * Hash matches `3UFKRD`
 * North Palace location matches the first version of the seed from my stream
 * Spells are different

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/d07b92f2-e5bc-46b5-9c0a-d0b330505fec)

**Comment by MiR4i** [comment]
So, I've been combing over this for hours and I'm not sure how I got the Life/Thunder loadout, but I can reproduce the Spell/Shield discrepancy.  Hopefully whatever's causing the different spells to be given is also caused by this same issue.

Follow the directions exactly as they are written to see the results that I got in the first post, but also see the notes at the bottom of this post for additional information.  I'm also changing the title of this thread, as `Beep Frequency` is not the culprit.

1. Restart App (may not be necessary, but let's start with a clean slate)
2. Flagset: `hEAAjqAFestUV3StMVeRfxUcumv@tNiyAAWA` | Seed: `9954`
3. `Generate ROM` - Seed will never generate; cancel out.
4. Restart App - Do not skip this step!
5. Seed: `4545`
6. `Generate ROM` - Wait for seed to generate
7. Rename file to something else (e.g. PostFail)
8. `Generate ROM` - Wait for seed to generate
9. Rename file to something else (e.g. PostSuccess)

Now, compare the files...

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/3006717d-9082-4e61-b44f-223392688794)


![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/503bcfa8-1139-4636-9942-4228d399fc0b)



Additional Notes:
 * Restarting the app after canceling (Step 4) is important - Without restarting, the issue doesn't seem to occur.
 * Not every flagset seems to produce the same issue.
   * Issue not related to `Chaos` climate; was able to reproduce with `Classic` climate.
 * The seed that you cancel out of to trigger the bug seems to be important - I tried other seeds and could not get the PostFail and PostSuccess ROMs to be different, but I didn't try too many alternatives.
 * Seed `4545` doesn't seem to be special - I was able to reproduce the issue with some other seeds, but not all; example:

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/a487af55-4a21-4a7d-98be-1ec410416540)

**Comment by Ellendar** [comment]
Just an update, I already know the kind of issue that causes this (some kind of state leakage in the palace generation). It doesn't have anything to do with any of the settings. You can start the rando, generate a seed, change nothing, generate the seed again, and it still happens. I spent a bunch of time last night trying to build a tool to make it easier to fix these kind of issues and failed. Maybe insight will strike today at work.

**Comment by Ellendar** [comment]
Fixed a couple cases related to linked rooms where the results weren't properly cloned.
