### ISSUE TITLE
Broken Palace Room Connections in GP (4.3 9f6a5d6J)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#165]
Vertical connections (elevators and drops) are sometimes completely, or partially broken in Great Palace.  Some drops will straight up kick you out of the palace (https://www.twitch.tv/videos/2060042636?t=0h32m52s), whereas others will drop you onto the ceiling of a room that was never meant as a landing room (https://www.twitch.tv/videos/2060042636?t=0h55m5s).  In addition, sometimes elevators will just teleport you into a room (https://www.twitch.tv/videos/2060042636?t=0h39m8s)

I haven't done a lot of testing, but this bug may occur when:
1) L7 drop/landing rooms are in the palace
2) The vertical split drop/one-up room is in the palace

The VOD links above are from the seed I played earlier (listed below), and they show both of those criteria from the list.

Version: [4.3 9f6a5d6](https://github.com/Ellendar/Z2Randomizer/commit/9f6a5d61121ab41228d79789097315209b5d9c17)
Flags: `hEAErqAFestUV1RrWVd7gQkcumv@tNiyAAWA`
Seed: `789382093`

**Comment by Ellendar** [comment]
Fixed this in a recent patch and forgot to reference the issue in the commit. Root cause was an incorrect connection in the bottom half of the L7 room.
