### ISSUE TITLE
Z2Randomizer.Core.ImpossibleException Error Generating Palaces (4.3.2)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#178]
The following seed and flags error out when attempting to generate palaces.

Flagset: `Q0SN6Fw4YRFs2NmCWVYAg+!59qtgbtJdAAFRA`
Seed: `280562335`

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/fb56d558-3dda-4e4d-b89f-8e1f51d06e6d)

**Comment by Ellendar** [comment]
Fixed the UI issue. Also added a validation rule so it doesn't break if you select remove tbird and random selects vanilla.
Eventually I should update it so remove Tbird works the way you expect with vanilla.

**Comment by Ellendar** [comment]
This could happen if you had a drop column that needed to continue dropping, but there were no drop zones left in the pool. This was a rare occurrence when you have no duplicate rooms on and a fairly small room pool like 4.0 only. 

Updated the logic to just politely fail if that happens and regenerate the palace set.
