### ISSUE TITLE
Standard Palace Layout Style Dropdown Incorrectly Controls "Thunderbird Required" Flag (4.3.2)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#180]
When the non-GP `Palace Style` drop-down is set to `Shuffled` or `Reconstructed`, it actives the `Thunderbird Required` flag, which also allows for further manipulating the `Remove Thunderbird` option when `Great Palace Style` is still set to `Vanilla`.  This is probably just left over from when the standard palace and great palace layout styles were just a single drop-down, and setting `Remove Thunderbird` to true results in an expected error:

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/d795f7aa-acc9-4e92-b7ca-00534a04e7d2)

**Comment by Ellendar** [comment]
Fixed the UI issue. Also added a validation rule so it doesn't break if you select remove tbird and random selects vanilla.
Eventually I should update it so remove Tbird works the way you expect with vanilla.
