### ISSUE TITLE
z2ft Integration

### ISSUE THREAD

**Issue by TheRealQuantam** [Ellendar/Z2Randomizer#200]
Integrate z2ft into the randomizer and add option for randomized music from a library derived from MM2 randomizer's music library.

Basic features of z2ft:
- Support for FamiTracker tracks that don't use DPCM or expansion chips (some limitations apply, but the MM2R library currently has over 1000 tracks)
- Up to 128 tracks per seed, though that's probably way more than will fit in the ROM (the z2ft demo for instance has 20 or so tracks)
- Per-encounter music selection. Per encounter music for fixed encounters is per map+area (e.g. each cave on the overworld map), while enemy encounters is per map+north/south+terrain+enemy size
- The set of tracks that can play are no longer limited by the area they appear in (the only exception is that the vanilla title theme can only be used during the title screen, as it uses a unique engine that will trample on in-game variables)
- Integration with Z2R could also allow per-boss music (this was left out of the base z2ft because the number of bosses and their object IDs is hack-specific).

I'll be doing most of this, but there are some executive decisions needed:
1. The set of uses. Each track in the library must be tagged with 1 or more uses, which determine where the randomizer can use that track in a given seed. A minimal set of uses would be overworld, town, fixed encounter, random encounter, palace; but it can be more fine-grained that than if desired. E.g. in MM2R we have the uses stage select, stage, boss, boss rush, credits.
2. How many tracks the randomizer should pick each seed for each usage. While it's theoretically possible to have 128 tracks (limited by ROM size), it might be preferable to only have a few different tracks per seed, so each seed feels unique.

**Comment by Ellendar** [comment]
I think your set of uses is a good start. I'd ideally like to add a couple to it

- Cave (This is kind of questionable maybe? but I feel like "cave music" is a thing with a lot of support
- Great Palace (GP has different music than the other palaces in vanilla and I think it makes sense to allow it to be different here)

I do need to try this with the rando at some point. If I don't get around to it bug me sometime.

**Comment by TheRealQuantam** [comment]
I'm hoping to have this in as a cosmetic option for the 2024 standard tournament. As such I'm hoping to have it done at least 1 month before the tournament for testing as people practice. 3 weeks from now should be plenty given the current state. The romhacking is pretty much done and the work on moving all the music randomization stuff from MM2 (or at least the parts I wrote) into an independent library that can be shared with other randomizers is coming along; that leaves integrating it into the Z2 randomizer.

For anyone who wants it, here's a patch for vanilla Z2 that is a demo of the z2ft capabilities.
[z2ftdemo.zip](https://github.com/user-attachments/files/16843737/z2ftdemo.zip)

**Comment by Ellendar** [comment]
We ended up backporting this to 4.3.X because we needed to do a bugfix patch. Might be some refinement/additional options for 4.4 but those can go on separate issues.
