### ISSUE TITLE
Setting "Attack Effectiveness" to "Low" Seems to Start Link with Zero Attack Strength (4.3.12)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#206]
If you specifically set your `Attack Effectiveness` to `Low`, Link is unable to kill anything with his sword at Attack 1.  For example, I could not kill any enemies in the overworld with over 50 stabs of my sword.  However, killing enemies with the Thunder spell to gain experience and level up to Attack 2, will give Link the ability to actually kill enemies with his sword. I cannot find a stream timestamp to provide a clip, but others can attest this happened after I was asked to roll a seed with low attack effectiveness.

I'll add that the `Shuffle Enemy HP` flag was enabled, but I am unsure whether that had any interaction with the `Attack Effectiveness` setting.  Ultimately, It seems like `Low` effectiveness is actually setting his Attack strength to zero (0), rather than one (1), at Attack 1.

**Comment by Ellendar** [comment]
Low attack 1-6 are just set to be equal to their level, but the attack levels are 0-indexed not 1-indexed so each level was 1 lower than expected, meaning 0 at L1.
