### ISSUE TITLE
Magic and Life "Starting Levels" Settings Not Acting As Expected (4.3.12)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#207]
The "Starting Levels" drop-down settings are not acting as one would expect. For example...

* Adjusting your starting Attack level is working as expected. (No issue)
* Adjusting your starting Magic level **also affects your Life level**.
* Adjusting your starting Life level **does not do anything**.

**Comment by Ellendar** [comment]
Export from Configuration to Properties was using the wrong value to set properties.StartLifeLvl.
