### ISSUE TITLE
Incorrect Text When Upstab/Downstab Locations Are Swapped (4.3.12)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#209]
When the locations of Upstab and Downstab are swapped, either when specifically enabling the option to swap or when the flag is 50/50, the related NPCs still provide their Vanilla text.

In other words, if the NPC in Mido gives the Upstab sword tech, he will still say that he's giving you Downstab, and the same is true for the NPC in Darunia.  I do believe this affects community text, as well.

**Comment by Ellendar** [comment]
4.4's text generation is different enough that I couldn't backport it, but I put in a quick fix that resolves this.
