### ISSUE TITLE
Add "+0" Heart Container Option For "Seed Max" Setting

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#210]
Recently, there have been times where I'll set a `Start Min` and `Start Max` range for my starting Heart Containers, but then I'd like that random number also be my `Seed Max`.  Right now, though, the lowest I can set that to would be `+1`, where I'd like to be able to have a `+0` option.

**Comment by Ellendar** [comment]
Also added +4, which is a backport from 4.4
