### ISSUE TITLE
Harder Carock Still Affecting Enemy Projectiles (4.3.12)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#213]
Posting this here as a reminder for both jrowe and the purpose of the changelog.

When `Harder Carock` is enabled, enemy projectiles can still be affected by his buffed up beam patterns.  To replicate:
* Engage Carock
* Die
* Exit his room and go explore the palace

From that point, enemy projectiles will take on similar behavior to Carock's sine wave beam pattern.

**Comment by Ellendar** [comment]
Jrowe pushed a fix for this with 4.3.13 but forgot to close the issue. If further issues are found we can reopen.
