### ISSUE TITLE
Saria Bot's "I Know Nothing" Response is Incorrect (4.3.12)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#214]
Since the bot in Saria was added into the NPC pool for possible hints, their "I know nothing" text is actually the Vanilla location for Bagu, which is irrelevant in the randomizer when playing a seed with a randomized overworld.

**Comment by Ellendar** [comment]
This was fixed in 4.4 but I bet I could backport it before we launch.

**Comment by Ellendar** [comment]
Backported the fix from 4.4
