### ISSUE TITLE
Cap Items/Spells Given While Shuffling

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#40]
Discussed this setting with Ellendar the other night, and am putting in a ticket for the changelog.

Add a cap to the items and/or spells that can be given to the player when shuffling either (or both).  Preliminary mock-up:

![image](https://user-images.githubusercontent.com/6069346/224548128-d26a3ac0-bb7a-45c0-87ca-6a27845c191d.png)

Additional Notes:

 * Should spells and items have separate controls for each, or just one setting to control both?
   * If separate, each group box will need to be lengthened to accommodate the new setting, otherwise a single setting can be included elsewhere (e.g. below the boxes).  I'm not opposed to just a single setting, as it may be easier to understand/configure, but...
   * If it's just a single setting to control both, does the numerical value chosen control both spells and abilities separately, or would it be a combined amount:
     * Static (4 = 4 Spells + 4 Items)
     * Divided Evenly (4 = 2 Spells + 2 Items)
     * Divided Randomly (4 = 1 Spell + 3 Items or 3 Spells + 1 Item or 2 Spells + 2 Items)
     * Should additional options be included to account for such conditions?
          ![image](https://user-images.githubusercontent.com/6069346/224549254-15894df4-bfa0-4c9b-b154-8eb144402816.png)

 * The label text is a WIP, but trying to keep it short and concise.
 * What values should be used?  It depends on how many bits we want to dedicate, but I also don't think the drop-down should include every value, 1-7, along with "No Limit."
 * I felt that "No Limit" was better to use than "Unlimited" - Not sure why, but it seems neater.

**Comment by MiR4i** [comment]
***Disclaimer: Reading this back, I feel that some of this may be poorly worded and confusing, but I can explain things better with visuals, if necessary.***

Worked on this idea a bit over the past day, and I think I've settled on the following two layouts:

![image](https://user-images.githubusercontent.com/6069346/230509071-f659fd73-f4f5-423a-b174-054f1fe43157.png)


I'm leaning toward the design in the "Spells" section where there's a bit of separation along with a divider, which should indicate to the user that there's a "sub-option" that is affected by something in the group.  The "Items" section mock-up has the connector lines that we've been adding elsewhere, but... A) it's a very long line connector that, in my opinion, looks a little gaudy at that distance, and B) moving these options closer to the main shuffle setting that activates them is going to put a gap between the main shuffle setting and the items/spells themselves.

Tooltip Text:
```
When shuffling, the randomizer will give no more
items than the value selected in the box below.
```
Note: More may need to be added to the tooltip depending on the logic decided upon down below (e.g. "This number is not a guarantee, but a max limit." and/or "Overrides do not affect this limit.").

### ***Are overrides considered as part of the restriction?***
If the above layout is adopted, does the limit that is chosen factor in any items that the user is already overriding, or are those also included into said limit?  For example, if we do the following: `Shuffle Items + Candle (Override) + Limit 2`, should it then be...

    A) Candle is included in the limit, resulting in only one additional item being shuffled into the inventory.
    B) Candle is not included in the limit, resulting in two additional items being shuffled into the inventory.

If option A, will an error be given if a user is overriding more items than they have set for their limit?

If option B, will overridden items/spells also be considered before randomly shuffling in everything else?  In other words, using the above example, will the Candle that is overriding the shuffle be considered as part of the possible item pool before being included into the inventory, possibly eating up one of the limited spots?

### ***Is the limit considered a guarantee, or just simply a limit?***
If a limit value is selected (e.g. 2), will it result in being guaranteed 2 items, or will it be a 0-2 chance roll?  I assume it will not be a guarantee, but it will help to clarify.

**Comment by Ellendar** [comment]
Pushing this to 4.4 so 4.3 can get out faster.

**Comment by Ellendar** [comment]
For now, this is limited to 2 separate limits, but I built it in such a way that it's pretty easy to do a combined limit later if we want to.
