### ISSUE TITLE
Bugged Item Room Still Exists (4.1.6)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#65]
The item room that is segmented from its pass-through counterpart is still bugged in 4.1.6.  I know the easy fix is to just move the item back one tile, but I threw out two re-designs—one minor and one major—that came to mind while looking at it, if you wanted a different take.

Flagset: `RAAN6AAFesXtWVXdt0g$8v4cYf4XT7AAWA`
Seed: `851324547`
Hash: `AAIK7A`
Room: `02:Palace1 02`

https://www.twitch.tv/videos/1843274535?t=1h41m47s

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/a6e80e3b-a26b-4c13-ba4d-a41a5f2c5727)

**Comment by Ellendar** [comment]
Somehow around the time jrowe did the modularization update, we rolled back to an older version of the palace rooms file that did not contain the fix for the palace rooms or the broken elevator room. I manually merged those changes into the current version of the palace rooms file.
