### ISSUE TITLE
Update releases system

### ISSUE THREAD

**Issue by Ellendar** [Ellendar/Z2Randomizer#71]
Currently the releases are just in the releases folder. With each release being 10+MB, over time this makes checking out the source takes increasing amounts of space/time. Past releases aren't needed with the source, so we should find a way to manage releases that doesn't involve downloading all of them each checkout.

**Comment by VelpaChallenger** [comment]
We can use GitHub Releases to include the .msi files there instead of in the Releases folder. This way, the releases are not included with the source.
