### ISSUE TITLE
Community Boss Rooms Appearing In Vanilla Reconstructed GP (4.1.8 Release)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#74]
Found a seed where Thunderbird's room was accessible via an elevator in a Vanilla Reconstructed Great Palace.

Version: `4.1.8 Release`
Flags: `hEAK0sALvstUN1TvUxg$8v9ttf9tT7AAWR`
Seed `886309989`
Hash `7QQQOK`
VOD Link: https://www.twitch.tv/videos/1859728786?t=2h11m55s

**Comment by Ellendar** [comment]
This specifically only happens with TBird's room. Just need to copy the solution for item rooms over to the GP palace creation start.
