### ISSUE TITLE
Incorrect NPC Dialog When Receiving Sword Techniques (4.2.1)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#81]
Each of the NPCs who teach sword techniques used their Vanilla text, but taught the opposite technique (sword tech locations were swapped, but NPC dialog was Vanilla).

Version: `4.2.1 3f3c979`
Flagset: `RAAN6AAFesXtN1Tdt0g$8v4cYf4XR7AAWA`
Seed: `590153194`
Hash: `3FUL85`

**Comment by Ellendar** [comment]
Added a swap to up/downstab text when community hints aren't applied.
