### ISSUE TITLE
Unable To Complete Seed (4.2.1)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#84]
This seed starts you out with access to Rauru (45 - Thunder), Medicine Cave (15 - Magic Container), the frontside of Jump Cave (12), and the backside of Saria (48 - Life).  There is no way for me to progress beyond Saria or Jump Cave.

Version: `4.2.1 3f3c979`
Flagset: `AAAJrAAFaqXtN1TcD2Hp8v4SX#4XR7AALy`
Seed: `898044324`
Hash: `NF3E6V`
Editor:
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/db2c95e1-245c-4efd-bcbb-08bebd0abdfe)

**Comment by Ellendar** [comment]
The reworked requirements-based overworld routing did not take into account whether a town was actually reachable for the sake of spellGet data.

Applied a likely super-inefficient fix for this i'll need to revisit later.
