### ISSUE TITLE
Setting Beep Frequency To "Off" Causes Game Crash (4.2.1)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#85]
Setting the "Beep Frequency" option to "Off" causes the game to crash when starting out in North Palace.

**Comment by Ellendar** [comment]
Digshake's original "no beep" fix changed one of the same addresses as the beep threshold modification, so it would half-undo the fix and crash.

Reversed the application order of beep frequency and threshold and it works fine now.

Eventually it may be correct to replace this with jrowe's method, which is instead:

![image](https://github.com/Ellendar/Z2Randomizer/assets/4948989/4f84fd89-4fc8-473c-8f0b-57fce5165ca3)
