### ISSUE TITLE
Alter Flags Field Behavior When Field Is Empty?

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#86]
I have a tendency to click into a text field, press Ctrl+A, and then follow it up with the Delete key to ensure that I'm removing everything out of it before pasting anything back into it, and I do this with the randomizer, as well.  I had no issue with this in version 4.0.4, but since the changeover to the updated version, deleting the flagset from the Flags field will produce a pop-up that states "Invalid Flags Entered!"

I assume that the updated behavior of how the flagset interacts with the user interface is the cause of this, and I'm wondering if the new behavior can be slightly altered so that it does not throw that error when the field is empty, at least until the field has lost focus (e.g. the user has clicked away from it)?

Going one step further, perhaps rather than throw the error when taking away focus from the empty Flags field, the field could just re-populate itself with the previous flagset that was there prior, before deletion.  This would reserve the "Invalid Flags" error for only when an invalid flagset is actually entered into the field.

**Comment by Ellendar** [comment]
FlagBox_TextChanged() no longer updates the state of the UI if the flag string is empty.
