### ISSUE TITLE
Incorrect Drop Room Exit Data (4.2.2)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#89]
Falling down a particular drop in Palace 6 kicks the player out of the palace, and the seed is technically broken as a result (gem duping required to beat it, but some items/spells unobtainable as a result).  P6 probably had the Flute, which blocked P5 under 3ER, but the editor shows that the amount of rooms in the palace is completely neutered from its normal, expected size.

Version: `4.2.2 b7e354e`
Flagset: `RAAJsAAFesXtN1TeM0g$8v4cYf4XT7AAVy`
Seed: `606109670`
Location: P6-47
Editor:
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/1984fba7-c69d-4b0f-8e3d-6682203a5f9c)

**Comment by Ellendar** [comment]
Pushing out a fix for thix, but it needs testing.
