### ISSUE TITLE
Horsehead Boss in Community Rooms Placed Too Far Forward (4.2.2/4.2.4)

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#91]
After removing Horsehead from being stuck in the floor in a community room (a few versions back), he is now too far forward, by two tiles, from where he normally should start.  This is true in both types of community rooms where he's present—pass-through and item rooms—but there is only one of the three rooms he can appear in, in the seed below: 

Version: `4.2.2 8149973`
Flagset: `RAAJsAAFesXtN1TdM0g$8v4cX#4XT7AATh`
Seed: `356162247`
Hash: `??????`
Room: `P2-30`
Example:
![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/5f36b3cb-1b00-4afc-9533-77f9429f5c76)

**Comment by Ellendar** [comment]
The horizonal position of horsehead did not change at all. If this is true, it was always true.

**Comment by MiR4i** [comment]
I have included two additional Horsehead item rooms from 4.0.4 to show the difference.

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/03422a1f-3b8f-4c39-aab2-fb88a3a7bd6b)

**Comment by MiR4i** [comment]
Version: `4.2.3 da69ef3`
Flagset: `AAAN6AAFesXtN1TeM0g$8v4cX#4XR7AAWA`
Seed: `596040942`
Hash: `F3QiOS`
Room: `P5-36`

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/38052f1b-864b-4db9-bc54-b95ec98e0c7b)

**Comment by Ellendar** [comment]
See #96

**Comment by MiR4i** [comment]
In the pass-through version of this boss room, Horsehead is still placed further forward than his typical starting position.

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/dbcd5782-f380-40a0-a9b5-b21b90cbf3ff)


There's no Horsehead pass-through room in 4.0.4 to directly compare to, but if we look at the pass-through Mazura room in P5 from the FDS version, you can see that the boss starts only three bricks away from the edge of the screen.

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/8df765d9-d45b-4995-a855-36a10a9aa6f8)

**Comment by Ellendar** [comment]
Do you have a seed that contains this room?

**Comment by MiR4i** [comment]
Totally forgot to add that info - This should be it:

Flagset: `RAAN6AAFesXtN1TeM0g$8v4cX#4XR7AALh`
Seed: `281950022`
Hash: `?????`
Room: `P5-41`

**Comment by Ellendar** [comment]
So this one isn't actually a community room. It's actually the vanilla P6 room that has a rebo. (P6-53). That's where the rebo is positioned, and rebo is more of a trigger than an enemy... Anyway I could update the room to do the same thing item rooms do where if there's a horsehead it automatically gets moved to horsehead's normal position, but unfortunately the current rooms system doesn't have any good way to specifically identify this room in the rooms format. So if I want to make that change, it's going to have to wait until after the room jam prep reformats the rooms file, so a 4.3 update.

**Comment by MiR4i** [comment]
This is probably the reason why there are no Horsehead pass-through boss rooms in 4.0.  Assumedly, digshake just didn't shuffle the room's enemy around, but he may have considered it and then figured that HH isn't much of a threat, at least compared to Rebonack, which just led him to leave the room alone.  I'll add that, if people eventually deemed it so, I wouldn't be sad to see HH's pass-through boss room go, since, more than anything, it's just a minor inconvenience to encounter him in there.

**Comment by Ellendar** [comment]
Updated the relevant room(s) to have HasBoss:true and IsBossRoom:false now that that is implemented properly as part of the palace generation cleanup.
