### ISSUE TITLE
Setting Encounter Rate to "Random" Results in "Invalid Flags" Error

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#94]
As per the title, setting the `Encounter Rate` setting on the `Overworld` tab to `Random` results in an "Invalid Flags" error.

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/f568bd62-1523-4280-90c3-d6efeed74afe)

**Comment by Ellendar** [comment]
The translation from flags to UI had support for EncounterRate.RANDOM, but the reverse did not.
