### ISSUE TITLE
Incorrect Default Startup Settings on Overworld Tab

### ISSUE THREAD

**Issue by MiR4i** [Ellendar/Z2Randomizer#95]
The `Shuffle Encounters` setting controls both the settings below it, but when the program is first run those settings will both be active, with one of them even starting out enabled.

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/10ff9c40-6290-48c9-8bba-8a921af015b9)

**Comment by Ellendar** [comment]
The initial settings are set based on what your saved flags are, so to debug this I need the flag string you had loaded.

**Comment by MiR4i** [comment]
On a fresh install, these are the flags that the program starts up with:
`RAhN6EAAFAViN1TRtcA$9TFCVAnTzFAmLh`

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/2bb4059c-b9c1-455a-a352-d00183b91f36)

**Comment by Ellendar** [comment]
Include lava in shuffle was being set after shuffle encounters, so the validation would run, turn include lava in shuffle off, and then the flag translation would just turn it back on. Swapped the order they're set.

**Comment by MiR4i** [comment]
I don't mean to be nitpicky, but this issue still seems to be occurring on 4.2.4:

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/1224f8f9-7816-41ab-adaf-4b3c41513841)

**Comment by Ellendar** [comment]
Shuffle encounters validation was only hooked to shuffleEncounters and not the other 2 fields, so if you changed from an empty default UI state to having include lava in shuffle, the validation didn't run. Added a hook to the handler into allow unsafe path encoutners and include lava in shuffle.

**Comment by MiR4i** [comment]
I'm going to re-open this because I've been seeing it lately when firing up fresh builds out of Visual Studio*, but `Include Lava in Shuffle` is defaulting to "enabled" before it should be allowed to, and here are the default settings I'm seeing on the first run:

![image](https://github.com/Ellendar/Z2Randomizer/assets/6069346/3cb8ba4a-9278-430d-a4df-9cc007acf5ca)


_*I don't know if a fresh build out of Visual Studio is exactly the same as a fresh install through the installer, so this may be an inaccurate report._

Default Flags: `RAhN6EAAFAViN1RLtBcZB+3mLEqBLnjLBJWA`
